//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smokeStacks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageLog
    {
        public string Message { get; set; }
        public Nullable<int> RoomID { get; set; }
        public int MessageID { get; set; }
        public string CreatorID { get; set; }
        public Nullable<System.DateTime> Recived { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Room Room { get; set; }
        public virtual MessageLog MessageLog1 { get; set; }
        public virtual MessageLog MessageLog2 { get; set; }
    }
}
