//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smokeStacks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateRoomMembership
    {
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int ID { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
