//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smokeStacks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.PrivateRoomMemberships = new HashSet<PrivateRoomMembership>();
        }
    
        public int RoomID { get; set; }
        [DisplayName("Name")]
        [Required] 
        public string RoomName { get; set; }
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string RoomPassword { get; set; }
        [Required] 
        public string Description { get; set; }
        public Nullable<int> CreatorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivateRoomMembership> PrivateRoomMemberships { get; set; }
        public virtual User User { get; set; }
    }
}
